# Generated by matugen from the current wallpaper. Shell-sourceable palette.
# Regenerate: ~/.config/hypr/scripts/apply-theme.sh
#
# Two spellings of every slot: `#rrggbb` for the consumers that want a CSS or
# wofi colour, and a bare `rrggbb` for the ones that do not take the hash --
# thornwatch hands its gradients straight to tte, which rejects it.
BASE='{{colors.surface.default.hex}}'
SURFACE='{{colors.surface_container.default.hex}}'
OVERLAY='{{colors.surface_container_high.default.hex}}'
MUTED='{{colors.outline.default.hex}}'
SUBTLE='{{colors.on_surface_variant.default.hex}}'
TEXT='{{colors.on_surface.default.hex}}'
LOVE='{{accent.love.hex}}'
GOLD='{{accent.gold.hex}}'
ROSE='{{accent.rose.hex}}'
PINE='{{accent.pine.hex}}'
FOAM='{{accent.foam.hex}}'
IRIS='{{accent.iris.hex}}'
SOURCE_COLOR='{{colors.source_color.default.hex}}'

BASE_BARE='{{colors.surface.default.hex_stripped}}'
SURFACE_BARE='{{colors.surface_container.default.hex_stripped}}'
OVERLAY_BARE='{{colors.surface_container_high.default.hex_stripped}}'
MUTED_BARE='{{colors.outline.default.hex_stripped}}'
SUBTLE_BARE='{{colors.on_surface_variant.default.hex_stripped}}'
TEXT_BARE='{{colors.on_surface.default.hex_stripped}}'
LOVE_BARE='{{accent.love.hexs}}'
GOLD_BARE='{{accent.gold.hexs}}'
ROSE_BARE='{{accent.rose.hexs}}'
PINE_BARE='{{accent.pine.hexs}}'
FOAM_BARE='{{accent.foam.hexs}}'
IRIS_BARE='{{accent.iris.hexs}}'

# The three Rose Pine "highlight" steps thornwatch uses, mapped onto the
# Material surface ladder.
HL_LOW_BARE='{{colors.surface_container_low.default.hex_stripped}}'
HL_MED_BARE='{{colors.surface_container_highest.default.hex_stripped}}'
HL_HIGH_BARE='{{colors.surface_bright.default.hex_stripped}}'
