-- Generated by matugen from the current wallpaper. Do not edit by hand.
-- Regenerate: ~/.config/hypr/scripts/apply-theme.sh
--
-- Consumed by ~/.config/fastfetch/lib/rp.lua, which converts these to SGR
-- sequences and exposes them as the RP table every fastfetch theme reads.
-- Hex rather than "38;2;r;g;b" on purpose: matugen's rgb filters are awkward
-- for the accent slots, and the conversion is two lines of Lua.
PALETTE_HEX = {
  base    = '{{colors.surface.default.hex}}',
  surface = '{{colors.surface_container.default.hex}}',
  overlay = '{{colors.surface_container_high.default.hex}}',
  muted   = '{{colors.outline.default.hex}}',
  subtle  = '{{colors.on_surface_variant.default.hex}}',
  text    = '{{colors.on_surface.default.hex}}',
  love    = '{{accent.love.hex}}',
  gold    = '{{accent.gold.hex}}',
  rose    = '{{accent.rose.hex}}',
  pine    = '{{accent.pine.hex}}',
  foam    = '{{accent.foam.hex}}',
  iris    = '{{accent.iris.hex}}',
  hlmed   = '{{colors.surface_container_highest.default.hex}}',
  hlhigh  = '{{colors.surface_bright.default.hex}}',
}
