-- Generated by matugen from the current wallpaper. Do not edit by hand.
-- Regenerate: ~/.config/hypr/scripts/apply-theme.sh
--
-- Bare hex strings, no `rgba(` wrapper: settings.lua composes its own alpha
-- suffixes so one palette entry can serve borders, shadows and text alike.
return {
    base    = "{{colors.surface.default.hex_stripped}}",
    surface = "{{colors.surface_container.default.hex_stripped}}",
    overlay = "{{colors.surface_container_high.default.hex_stripped}}",
    muted   = "{{colors.outline.default.hex_stripped}}",
    subtle  = "{{colors.on_surface_variant.default.hex_stripped}}",
    text    = "{{colors.on_surface.default.hex_stripped}}",
    love    = "{{accent.love.hexs}}",
    gold    = "{{accent.gold.hexs}}",
    rose    = "{{accent.rose.hexs}}",
    pine    = "{{accent.pine.hexs}}",
    foam    = "{{accent.foam.hexs}}",
    iris    = "{{accent.iris.hexs}}",
}
