-- Generated by matugen from the current wallpaper. Do not edit by hand.
-- Regenerate: ~/.config/hypr/scripts/apply-theme.sh
--
-- Fed to rose-pine.nvim as a `palette.main` override (see lua/plugins/custom.lua).
-- The slot names are rose-pine's own, so the whole colorscheme -- syntax,
-- treesitter, LSP, and every plugin integration it ships -- is recoloured from
-- the wallpaper without hand-writing a single highlight group.
return {
  _nc            = "{{colors.surface_container_low.default.hex}}",
  base           = "{{colors.surface.default.hex}}",
  surface        = "{{colors.surface_container.default.hex}}",
  overlay        = "{{colors.surface_container_high.default.hex}}",
  muted          = "{{colors.outline.default.hex}}",
  subtle         = "{{colors.on_surface_variant.default.hex}}",
  text           = "{{colors.on_surface.default.hex}}",
  love           = "{{accent.love.hex}}",
  gold           = "{{accent.gold.hex}}",
  rose           = "{{accent.rose.hex}}",
  pine           = "{{accent.pine.hex}}",
  foam           = "{{accent.foam.hex}}",
  iris           = "{{accent.iris.hex}}",
  leaf           = "{{accent.pine.hex}}",
  highlight_low  = "{{colors.surface_container_low.default.hex}}",
  highlight_med  = "{{colors.surface_container_highest.default.hex}}",
  highlight_high = "{{colors.surface_bright.default.hex}}",
  none           = "NONE",
}
