pragma Singleton

import QtQuick
import Quickshell

// Generated by matugen from the current wallpaper. Do not edit by hand.
// Regenerate: ~/.config/hypr/scripts/apply-theme.sh
//
// Theme.qml aliases these, so every QML surface picks the new palette up on
// the next `qs reload` without any of them importing matugen directly.
Singleton {
    readonly property color base:       "{{colors.surface.default.hex}}"
    readonly property color surface:    "{{colors.surface_container.default.hex}}"
    readonly property color overlay:    "{{colors.surface_container_high.default.hex}}"
    readonly property color muted:      "{{colors.outline.default.hex}}"
    readonly property color subtle:     "{{colors.on_surface_variant.default.hex}}"
    readonly property color text:       "{{colors.on_surface.default.hex}}"
    readonly property color love:       "{{accent.love.hex}}"
    readonly property color gold:       "{{accent.gold.hex}}"
    readonly property color rose:       "{{accent.rose.hex}}"
    readonly property color pine:       "{{accent.pine.hex}}"
    readonly property color pineBright: "{{colors.primary.default.hex}}"
    readonly property color foam:       "{{accent.foam.hex}}"
    readonly property color iris:       "{{accent.iris.hex}}"
}
