preload = /home/h3bzzz/Pictures/wallpapers/brasil_copa.png
wallpaper = desc:LG Electronics LG HDR QHD 307NTJJ1E036,/home/h3bzzz/Pictures/wallpapers/brasil_copa.png
wallpaper = desc:ViewSonic Corporation VX2252 Series TVR1940A0447,/home/h3bzzz/Pictures/wallpapers/brasil_copa.png
splash = false
ipc = true
