[general]
framerate = 60
bars = 12
autosens = 1
overshoot = 20

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 1000

[input]
method = pulse
source = auto

[smoothing]
noise_reduction = 77
