unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Start at 1
set -g base-index 1
setw -g pane-base-index 1

# Renumber
set -g renumber-windows on

# Mouse Support
set -g mouse on

# Scroll Buffer
set -g history-limit 50000

# Color Support
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Faster Cmd
set -s escape-time 0

# Display
set -g display-time 2000
set -g status-interval 5
set -g focus-events on

# Rose Pine Colors
base=#191724
surface=#1f1d2e
overlay=#26233a
muted=#6e6a86
subtle=#908caa
text=#e0def4
love=#eb6f92
gold=#f6c177
rose=#ebbcba
pine=#31748f
foam=#9ccfd8
iris=#c4a7e7
hl=#544f67

# Key Binds
bind r source-file ~/h3bzzz-dotfiles/config/tmux/tmux.conf \; display "Reloaded!"

# Split Panes
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Switch Panes
bind -n M-left select-pane -L
bind -n M-right select-pane -R
bind -n M-up select-pane -U
bind -n M-down select-pane -D

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

setw -g mode-keys vi

bind [ copy-mode

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "wl-copy"

bind ] run "wl-paste | tmux load-buffer - && tmux paste-buffer"
bind p run "wl-paste | tmux load-buffer - && tmux paste-buffer"

# Style
set -g status-style "fg=$subtle,bg=$surface"
set -g pane-border-style "fg=$overlay,bg=$base"
set -g pane-active-border-style "fg=$foam,bg=$base"
set -g message-style "bg=$pine,fg=$text"

setw -g window-status-style "fg=$subtle,bg=$overlay"
setw -g window-status-current-style "fg=$base,bg=$foam"
setw -g window-status-activity-style "fg=$base,bg=$iris"
setw -g window-status-separator ""

set -g status-left-length 60
set -g status-right-length 120

# Formats
set -g status-left "#[fg=$base,bg=$foam] #S #[fg=$foam,bg=$surface,nobold,nounderscore,noitalics]"
set -g status-right "#[fg=$foam,bg=$surface]#[fg=$base,bg=$foam] %H:%M  %d-%b-%y "

setw -g window-status-format " #[fg=$overlay,bg=$surface]#[fg=$subtle,bg=$overlay] #I  #W #[fg=$overlay,bg=$surface]"
setw -g window-status-current-format " #[fg=$surface,bg=$surface]#[fg=$base,bg=$foam] #I  #W #[fg=$foam,bg=$surface]"

setw -g clock-mode-colour "$foam"

setw -g mode-style "fg=$base,bg=$foam"

setw -g monitor-activity on
set -g visual-activity off
set -g set-titles on
set -g set-titles-string "#T"

set -gq allow-passthrough on
set-option -g focus-events on
